import type {NextFunction, Request, RequestHandler, Response} from 'express';
import {
  EXECUTION_CAUSATION_HEADER,
  EXECUTION_CORRELATION_HEADER,
  createInboundExecutionContext,
  runWithExecutionContext,
  type ExecutionContext,
} from '../../lib/observability/executionContext.js';

export const EXECUTION_REQUEST_HEADER = 'x-request-id';

/**
 * Compatibility shape for legacy handlers while the application is migrated to
 * `requireExecutionContext()`. These identifiers are diagnostic metadata only;
 * they must never authorize a request or serve as an idempotency credential.
 */
export type HttpExecutionRequest = Request & {
  correlationId: string;
  requestId: string;
  causationId?: string;
  executionContext: ExecutionContext;
  user?: {id?: number | string};
};

export type HttpExecutionCompletion = Readonly<{
  request: HttpExecutionRequest;
  response: Response;
  context: ExecutionContext;
  durationMs: number;
}>;

export type HttpExecutionContextMiddlewareOptions = Readonly<{
  onFinish?: (completion: HttpExecutionCompletion) => void;
}>;

/**
 * Establishes one validated execution context per HTTP request. A valid caller
 * correlation can cross the boundary; the local operation/request identifier
 * is always generated by Encho. Causation is reflected only when the caller
 * supplied a valid parent operation identifier.
 */
export function createHttpExecutionContextMiddleware(
  options: HttpExecutionContextMiddlewareOptions = {},
): RequestHandler {
  return (request: Request, response: Response, next: NextFunction): void => {
    const context = createInboundExecutionContext(request.headers, 'HTTP');
    const contextualRequest = request as HttpExecutionRequest;

    contextualRequest.correlationId = context.correlationId;
    contextualRequest.requestId = context.operationId;
    contextualRequest.executionContext = context;
    if (context.causationId) contextualRequest.causationId = context.causationId;

    response.setHeader(EXECUTION_CORRELATION_HEADER, context.correlationId);
    response.setHeader(EXECUTION_REQUEST_HEADER, context.operationId);
    if (context.causationId) {
      response.setHeader(EXECUTION_CAUSATION_HEADER, context.causationId);
    }

    const startedAt = Date.now();
    response.once('finish', () => {
      options.onFinish?.(Object.freeze({
        request: contextualRequest,
        response,
        context,
        durationMs: Date.now() - startedAt,
      }));
    });

    runWithExecutionContext(context, next);
  };
}
