import React from 'react';
import { ArrowLeft, CheckCircle2, CalendarDays, MapPin, Printer } from 'lucide-react';
import type { Listing } from '../types';

interface BookingPageProps {
  listing: Listing;
  bookingDetails: {
    bookingId?: string; status?: string; moveInDate: string; checkOutDate?: string;
    configuration: string; name: string; phone: string; totalRent: number;
    roomTier?: string; adultsCount?: number; childrenCount?: number;
  };
  onBackToHome: () => void;
}
export const BookingPage: React.FC<BookingPageProps> = ({ listing, bookingDetails: b, onBackToHome }) => {
  const confirmed = Boolean(b.bookingId && b.status?.toLowerCase() === 'confirmed');
  const date = (value?: string) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleDateString('en-IN', { year: 'numeric', month: 'short', day: 'numeric' }) : 'Not recorded';
  return <main className="min-h-screen bg-stone-50 px-4 py-10 text-zinc-900">
    <article className="max-w-2xl mx-auto bg-white rounded-3xl border border-zinc-200 p-6 md:p-10 space-y-8">
      <button onClick={onBackToHome} className="flex items-center gap-2 min-h-11 text-sm print:hidden"><ArrowLeft size={18} /> Return to Encho</button>
      <header>
        {confirmed && <CheckCircle2 size={36} className="text-emerald-700 mb-4" />}
        <h1 className="text-3xl font-semibold tracking-tight">{confirmed ? 'Your stay is confirmed.' : 'Reservation details'}</h1>
        <p className="text-zinc-600 mt-3">{confirmed ? 'Keep this reference for your stay and any support requests.' : 'Open your reservations to check the latest booking status.'}</p>
      </header>
      {b.bookingId && <div className="rounded-xl bg-emerald-50 p-4"><span className="text-xs uppercase tracking-wider">Booking reference</span><p className="font-mono text-lg mt-1">{b.bookingId}</p></div>}
      <section className="space-y-4">
        <h2 className="text-xl font-semibold">{listing.title}</h2>
        <p className="flex gap-2 text-zinc-600"><MapPin size={18} />{listing.address || listing.city}</p>
        <p className="flex gap-2"><CalendarDays size={18} />{date(b.moveInDate)} — {date(b.checkOutDate)}</p>
        <dl className="grid grid-cols-2 gap-4 text-sm">
          <dt className="text-zinc-500">Room</dt><dd>{b.configuration}</dd>
          <dt className="text-zinc-500">Guest</dt><dd>{b.name}</dd>
          <dt className="text-zinc-500">Booking total</dt><dd>{new Intl.NumberFormat('en-IN', { style: 'currency', currency: listing.currency || 'INR' }).format(b.totalRent)}</dd>
        </dl>
      </section>
      <section className="border-t pt-6"><h2 className="font-semibold">Before you arrive</h2><p className="text-sm text-zinc-600 mt-2">Use your Encho inbox to coordinate arrival with the host. Access instructions and Wi-Fi details are provided by the property; they are not generated by Encho.</p></section>
      <button onClick={() => window.print()} className="flex items-center gap-2 min-h-11 border rounded-xl px-4 text-sm print:hidden"><Printer size={18} /> Print booking summary</button>
    </article>
  </main>;
};
export default BookingPage;
