import React,{useEffect,useState} from 'react';
import {AdtechMap,type FeederPin} from './AdtechMap';
import {marketingRequest} from './api';
import type {StrategyGeographyEvidence} from '../../src/shared/adtech/contracts';
type Entry={kind:'PROVIDER_CITY_RADIUS';query:string;providerKey:string;radiusKm:number}|{kind:'COORDINATE_RADIUS';label:string;latitude:number;longitude:number;radiusKm:number}|{kind:'PROVIDER_REGION_EXCLUSION';query:string;providerKey:string};
export function AdtechCorridors({run,busy}:{run:(path:string,body:unknown,method?:string)=>Promise<unknown>;busy:boolean}){
 const [newName,setNewName]=useState(''),[newKey,setNewKey]=useState(''),[newDistrict,setNewDistrict]=useState('');
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[destination,setDestination]=useState(''),[provider,setProvider]=useState('META'),[tier,setTier]=useState('BUDGET');
 const [entries,setEntries]=useState<Entry[]>([]),[query,setQuery]=useState(''),[kind,setKind]=useState<'CITY'|'DISTRICT'>('CITY'),[results,setResults]=useState<Array<{key:string;name:string}>>([]),[reason,setReason]=useState(''),[latitude,setLatitude]=useState(''),[longitude,setLongitude]=useState(''),[radius,setRadius]=useState(''),[label,setLabel]=useState(''),[searching,setSearching]=useState(false);
 const load=()=>marketingRequest<any>('/admin/adtech/corridors').then(setData).catch(e=>setError(e.message));
 useEffect(()=>{void load();},[]);
 const versions=data?.versions.filter((v:any)=>String(v.corridor_id)===destination&&v.provider===provider&&v.tier_code===tier)??[];const latest=versions[0];
 const published=data?.published.find((v:any)=>String(v.corridor_id)===destination&&v.provider===provider&&v.tier_code===tier);
 const identity=data?.corridors.find((v:any)=>String(v.id)===destination);
 useEffect(()=>{
  const geography=(latest?.geography??[]) as StrategyGeographyEvidence[];
  setEntries(geography.map(g=>g.kind==='COORDINATE_RADIUS'?{kind:g.kind,label:g.label,latitude:g.latitude,longitude:g.longitude,radiusKm:g.radiusKm}:g.kind==='PROVIDER_CITY_RADIUS'?{kind:g.kind,query:g.label,providerKey:g.providerKey,radiusKm:g.radiusKm}:{kind:g.kind,query:identity?.district_name??g.label,providerKey:g.providerKey}));
  setResults([]);setReason('');
 },[latest?.id,destination,provider,tier,identity?.district_name]);
 async function search(){setSearching(true);setError('');try{const result=await marketingRequest<{locations:Array<{key:string;name:string}>}>(`/admin/adtech/geography?${new URLSearchParams({provider,q:query,kind})}`);setResults(result.locations);}catch(e){setError((e as Error).message);}finally{setSearching(false);}}
 async function save(){setError('');try{await run(`/corridors/${destination}`,{provider,tier,expectedVersion:latest?.version??0,entries,reason},'PUT');await load();}catch(e){setError((e as Error).message);}}
 async function publish(){try{await run(`/corridors/${destination}/publish`,{versionId:latest.id,expectedVersionId:published?.version_id??null,reason});await load();}catch(e){setError((e as Error).message);}}
 const savedPins=((latest?.geography??[]) as StrategyGeographyEvidence[]).filter(g=>g.kind!=='PROVIDER_REGION_EXCLUSION');
 const pins=entries.flatMap<FeederPin>((e)=>e.kind==='COORDINATE_RADIUS'?[e]:e.kind==='PROVIDER_CITY_RADIUS'?savedPins.filter(g=>'providerKey'in g&&g.providerKey===e.providerKey).map(g=>({...g,label:e.query,radiusKm:e.radiusKm})):[]);
 return <section className="adt-card"><h2>Destination corridors</h2><p>Resolve public feeder locations and an exact district before releasing a corridor. Proposed coordinates have no spending authority.</p>{error&&<p role="alert">{error}</p>}
  <details><summary>Register a destination</summary><div className="mkt-fields"><label>Destination name<input value={newName} onChange={e=>setNewName(e.target.value)}/></label><label>Stable destination key<input value={newKey} onChange={e=>setNewKey(e.target.value)} pattern="[a-z0-9]+(-[a-z0-9]+)*"/></label><label>Exact district name<input value={newDistrict} onChange={e=>setNewDistrict(e.target.value)}/></label><p>Enter the reason in the change field below. Country and district identity must still be verified when saving geography.</p><button type="button" className="mkt-secondary" disabled={busy||reason.trim().length<10||!newName||!newKey||!newDistrict} onClick={()=>void run('/corridors',{name:newName,destinationKey:newKey,districtName:newDistrict,aliases:[],reason}).then(()=>load()).catch(e=>setError(e.message))}>Register destination</button></div></details><fieldset disabled={busy} className="adt-profile mkt-fields"><label>Destination<select aria-label="Destination" value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Select destination</option>{data?.corridors.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
  <div className="mkt-field-pair"><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value)}><option>META</option><option>GOOGLE</option></select></label><label>Tier<select value={tier} onChange={e=>setTier(e.target.value)}>{['BUDGET','COMFORT','PREMIUM'].map(t=><option key={t}>{t}</option>)}</select></label></div>
  <AdtechMap pins={pins} onSelect={(lat,lng)=>{setLatitude(String(lat));setLongitude(String(lng));}}/>
  {identity&&<p className="adt-lock">Required exclusion: {identity.district_name} district</p>}
  <div className="mkt-field-pair"><label>Location lookup<select value={kind} onChange={e=>setKind(e.target.value as 'CITY'|'DISTRICT')}><option value="CITY">Feeder city</option><option value="DISTRICT">Destination district exclusion</option></select></label><label>Provider location name<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={120}/></label></div>
  <button type="button" className="mkt-secondary" disabled={searching||query.trim().length<2} onClick={()=>void search()}>{searching?'Searching…':'Search provider locations'}</button>
  {results.map(result=><button type="button" className="mkt-secondary" key={result.key} onClick={()=>setEntries(values=>[...values,kind==='DISTRICT'?{kind:'PROVIDER_REGION_EXCLUSION',query,providerKey:result.key}:{kind:'PROVIDER_CITY_RADIUS',query,providerKey:result.key,radiusKm:Number(radius)}])}>{result.name} · {result.key} · add {kind==='DISTRICT'?'exclusion':'city using radius below'}</button>)}
  <details><summary>Add a public coordinate feeder</summary><div className="mkt-fields"><label>Feeder label<input value={label} onChange={e=>setLabel(e.target.value)}/></label><div className="mkt-field-pair"><label>Latitude<input type="number" step="any" min={-90} max={90} value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label>Longitude<input type="number" step="any" min={-180} max={180} value={longitude} onChange={e=>setLongitude(e.target.value)}/></label></div></div></details>
  <label>Radius for new feeder · km<input type="number" step="any" min={1} max={1000} value={radius} onChange={e=>setRadius(e.target.value)}/></label>
  <button type="button" className="mkt-secondary" disabled={!label||latitude===''||longitude===''||!(Number(radius)>0)} onClick={()=>setEntries(values=>[...values,{kind:'COORDINATE_RADIUS',label,latitude:Number(latitude),longitude:Number(longitude),radiusKm:Number(radius)}])}>Add coordinate feeder</button>
  <ol>{entries.map((entry,index)=><li key={`${entry.kind}:${index}`}><div className="adt-actions"><span>{entry.kind==='COORDINATE_RADIUS'?entry.label:entry.query} · {entry.kind==='PROVIDER_REGION_EXCLUSION'?'excluded district':`${entry.radiusKm} km`}</span><button type="button" className="mkt-secondary" onClick={()=>setEntries(values=>values.filter((_,i)=>i!==index))}>Remove entry {index+1}</button></div>{entry.kind!=='PROVIDER_REGION_EXCLUSION'&&<label>Entry {index+1} radius · km<input type="number" value={entry.radiusKm} onChange={e=>setEntries(values=>values.map((v,i)=>i===index?{...entry,radiusKm:Number(e.target.value)}:v))}/></label>}</li>)}</ol>
  <label>Reason for change<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={10} maxLength={2000}/></label>
  <div className="adt-actions"><button type="button" className="mkt-primary" disabled={!destination||reason.trim().length<10||entries.length<2} onClick={()=>void save()}>Verify and save corridor version</button><button type="button" className="mkt-secondary" disabled={!latest||reason.trim().length<10||latest.id===published?.version_id} onClick={()=>void publish()}>Publish saved corridor v{latest?.version??'—'}</button></div>
  <p className="mkt-caption">Saving performs independent country and district checks plus provider resolution. Publishing uses the saved version; unsaved form edits are not included.</p>
 </fieldset></section>;
}
