import React,{useEffect,useRef,useState} from 'react';
import {marketingRequest,humanStatus,money} from './api';
import {Notice} from './StudioShared';
import type {StudioCampaign,MarketingListing} from './types';
type Member={id:string;listingId:number;listingTitle:string;state:string;version:number;campaignId:number|null;contributionMinor:string|null;servedExposures:number;factHash:string|null;hasReservation:boolean};
type Pool={id:string;destination:string;title:string;state:string;version:number;startsAt:string;endsAt:string;stayStart:string;stayEnd:string;members:Member[]};
export function DestinationPools({admin=false,campaigns=[],listings=[]}:{admin?:boolean;campaigns?:StudioCampaign[];listings?:MarketingListing[]}){
 const [open,setOpen]=useState(false),[pools,setPools]=useState<Pool[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [destination,setDestination]=useState('wayanad'),[title,setTitle]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[stayStart,setStayStart]=useState(''),[stayEnd,setStayEnd]=useState('');
 const keys=useRef(new Map<string,string>());
 async function load(signal?:AbortSignal){const response=await marketingRequest<{pools:Pool[]}>('/destination-pools',{signal});setPools(response.pools);}
 useEffect(()=>{if(!open)return;const c=new AbortController();void load(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[open]);
 async function act(path:string,body:unknown){setBusy(true);setError('');setNotice('');const intent=path+JSON.stringify(body);if(!keys.current.has(intent))keys.current.set(intent,crypto.randomUUID());try{const response=await marketingRequest<any>(path,{method:'POST',headers:{'Idempotency-Key':keys.current.get(intent)!},body:JSON.stringify(body)});keys.current.delete(intent);await load();setNotice('Destination request recorded.');if(response.url){const u=new URL(response.url);if(u.protocol!=='https:'||!['checkout.stripe.com','rzp.io','rzp.co','razorpay.com','pages.razorpay.com'].includes(u.hostname))throw new Error('Unexpected checkout destination.');window.location.assign(u.href);}return response;}catch(e){setError(e instanceof Error?e.message:'Destination request failed.');return null;}finally{setBusy(false);}}
 return <section className="mkt-panel mkt-pools"><div className="mkt-section-heading"><div><span className="mkt-eyebrow">Optional destination campaigns</span><h3>A shared destination. Your own funds.</h3></div><button className="mkt-secondary" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Close':'Explore destination flights'}</button></div>
  {open&&<><p>Wayanad · Coorg · Goa. Featured collection placement rotates by contribution among eligible stays. This does not guarantee ad-network impressions or bookings.</p><p className="mkt-caption">Minimum media contribution ₹1,000 per flight. Maximum authorized destination media spend ₹10,000 per day. Fees appear separately in your quote. Full occupancy pauses your allocation; your funds are never transferred to another host.</p>
  {error&&<Notice error>{error}</Notice>}{notice&&<Notice>{notice}</Notice>}
  {admin&&<form className="mkt-fields" onSubmit={e=>{e.preventDefault();void act('/admin/destination-pools',{destination,title,startsAt:`${start}T00:00:00+05:30`,endsAt:`${end}T23:59:59+05:30`,stayStart,stayEnd});}}><h4>Create a bounded destination flight</h4><label>Destination<select value={destination} onChange={e=>setDestination(e.target.value)}><option value="wayanad">Wayanad</option><option value="coorg">Coorg</option><option value="goa">Goa</option></select></label><label>Collection title<input required minLength={3} maxLength={100} value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="mkt-field-row"><label>Advertising starts · India Time<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Advertising ends · India Time<input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="mkt-field-row"><label>Guest arrival window starts<input type="date" required value={stayStart} onChange={e=>setStayStart(e.target.value)}/></label><label>Guest stay ends<input type="date" required value={stayEnd} onChange={e=>setStayEnd(e.target.value)}/></label></div><button className="mkt-primary" disabled={busy}>Create draft flight</button></form>}
  {!pools.length&&<p>No destination invitations or flights are available for this account.</p>}
  {pools.map(pool=><PoolCard key={pool.id} pool={pool} admin={admin} busy={busy} act={act} campaigns={campaigns} listings={listings}/>)}</>}
 </section>;
}
function PoolCard({pool,admin,busy,act,campaigns,listings}:{pool:Pool;admin:boolean;busy:boolean;act:(p:string,b:unknown)=>Promise<any>;campaigns:StudioCampaign[];listings:MarketingListing[]}){
 const [listing,setListing]=useState(''),[reason,setReason]=useState('');
 return <article className="mkt-pool-card"><div className="mkt-section-heading"><h4>{pool.title}</h4><span className="mkt-pill">{humanStatus(pool.state)}</span></div><p>{new Date(pool.startsAt).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})} – {new Date(pool.endsAt).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})} · India Time</p><a href={`/explore/${pool.destination}`} target="_blank" rel="noreferrer">View collection</a>
  {admin&&<div className="mkt-fields"><label>Operational reason<input value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label><div className="mkt-review-actions">{({DRAFT:['OPEN','CLOSED'],OPEN:['ACTIVE','CLOSED'],ACTIVE:['PAUSED','CLOSED'],PAUSED:['ACTIVE','CLOSED']}[pool.state]??[]).map(state=><button key={state} className="mkt-secondary" disabled={busy||reason.trim().length<10} onClick={()=>void act(`/admin/destination-pools/${pool.id}/state`,{state,version:pool.version,reason})}>{state==='ACTIVE'?'Open collection allocation':humanStatus(state)}</button>)}</div><p className="mkt-caption">Opening collection allocation does not publish a provider campaign or spend funds.</p>{['DRAFT','OPEN'].includes(pool.state)&&<><label>Invite a published property<select value={listing} onChange={e=>setListing(e.target.value)}><option value="">Select a property</option>{listings.filter(l=>l.publicationStatus==='published').map(l=><option value={l.id} key={l.id}>{l.title}</option>)}</select></label><button className="mkt-secondary" disabled={busy||!listing} onClick={()=>void act(`/admin/destination-pools/${pool.id}/invitations`,{listingId:Number(listing)})}>Invite owner</button></>}</div>}
  {pool.members.map(m=><MemberCard key={`${m.id}:${m.version}`} member={m} admin={admin} busy={busy} act={act} campaigns={campaigns}/>)}
 </article>;
}
function MemberCard({member:m,admin,busy,act,campaigns}:{member:Member;admin:boolean;busy:boolean;act:(p:string,b:unknown)=>Promise<any>;campaigns:StudioCampaign[]}){
 const [campaign,setCampaign]=useState(''),[accepted,setAccepted]=useState(false),[facts,setFacts]=useState<any>(null),[reason,setReason]=useState(''),[error,setError]=useState('');
 const selected=campaigns.find(c=>String(c.id)===campaign),bound=campaigns.find(c=>String(c.id)===String(m.campaignId));
 return <section className="mkt-panel"><h4>{m.listingTitle}</h4><p>{humanStatus(m.state)}{m.contributionMinor?` · ${money(m.contributionMinor,'INR')} media contribution`:''}</p><p className="mkt-caption">{m.servedExposures} featured collection responses served. A served page is not proof it was viewed, or an ad-network impression.</p>
  {!admin&&m.state==='INVITED'&&<div className="mkt-fields"><label>Approved, unfunded contribution plan<select value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">Choose your reviewed plan</option>{campaigns.filter(c=>Number(c.listingId)===m.listingId&&c.status==='APPROVED'&&!c.quote).map(c=><option key={c.id} value={c.id}>{c.title} · {money(c.mediaBudgetMinor,'INR')}</option>)}</select></label><label className="mkt-checkbox"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I opt into contribution-weighted collection placement under HARVO-033. If paid enrollment opens, this plan will fund this destination flight and will not run as a separate property ad. I understand that there is no guaranteed delivery, my contribution remains separate, and fees appear in the quote before payment.</span></label><button className="mkt-primary" disabled={busy||!selected||!accepted} onClick={()=>void act(`/pool-memberships/${m.id}/consent`,{version:m.version,campaignId:Number(selected!.id),campaignRevision:selected!.revision,policyVersion:1,disclosureAccepted:true})}>Accept invitation</button></div>}
  {admin&&m.state==='CONSENTED'&&<div className="mkt-fields"><button className="mkt-secondary" disabled={busy} onClick={()=>{setError('');void marketingRequest(`/listings/${m.listingId}/marketing-facts`).then(setFacts).catch(e=>setError(e.message));}}>Read current property facts</button>{facts&&<><ul className="mkt-notes">{facts.facts.map((f:any)=><li key={f.id}>{f.field}: {f.value}</li>)}</ul><label>Evidence supporting villa quality and destination eligibility<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label><label className="mkt-checkbox"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I independently checked this villa’s quality, destination, and published evidence.</span></label><button className="mkt-primary" disabled={busy||!accepted||reason.trim().length<20} onClick={()=>void act(`/admin/pool-memberships/${m.id}/review`,{version:m.version,factHash:facts.factHash,verifiedVilla:true,verifiedDestination:true,reason})}>Record eligibility review</button></>}{error&&<Notice error>{error}</Notice>}</div>}
  {!admin&&bound&&['CONSENTED','ELIGIBLE'].includes(m.state)&&<Notice>Paid destination enrollment is not open. Your invitation does not charge you or publish advertising.</Notice>}
  {m.state==='PAUSED'&&<button className="mkt-secondary" disabled={busy} onClick={()=>void act(`/pool-memberships/${m.id}/resume`,{})}>Check eligibility & resume allocation</button>}
  {!m.hasReservation&&!bound?.quote&&['INVITED','CONSENTED','ELIGIBLE','PAUSED'].includes(m.state)&&<button className="mkt-secondary" disabled={busy} onClick={()=>void act(`/pool-memberships/${m.id}/withdraw`,{})}>Withdraw invitation</button>}
  {['ACTIVE','ELIGIBLE'].includes(m.state)&&<button className="mkt-secondary" disabled={busy} onClick={()=>void act(`/pool-memberships/${m.id}/pause`,{})}>Pause allocation</button>}
 </section>;
}
