import React,{useEffect,useState} from 'react';
import {Activity,RefreshCw} from 'lucide-react';
import {marketingRequest,humanStatus,observedTime} from './api';
import {Notice} from './StudioShared';
type Operations={observedAt:string;jobs:{id:string;campaign_id:number|null;kind:string;state:string;attempts:number;last_error:string|null}[];queues:{kind:string;state:string;count:number;oldest_created_at:string;expired_leases:number}[]};
type Readiness={observedAt:string;settlement:{configured:boolean};conversions:{enabled:boolean;blockers:string[];canonicalSource?:string;google?:string;meta?:string;limits?:string[]}};
export function OperationsPanel(){
 const [open,setOpen]=useState(false),[result,setResult]=useState<{operations:Operations;readiness:Readiness}|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!open)return;const controller=new AbortController();setLoading(true);
  Promise.all([marketingRequest<Operations>('/admin/operations',{signal:controller.signal}),marketingRequest<Readiness>('/admin/readiness',{signal:controller.signal})]).then(([operations,readiness])=>{if(!Array.isArray(operations.jobs)||!Array.isArray(operations.queues)||!Array.isArray(readiness.conversions?.blockers))throw new Error('Operational evidence is incomplete.');if(!controller.signal.aborted){setResult({operations,readiness});setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Operational evidence is unavailable.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
 },[open,refresh]);
 return <section className="mkt-panel"><div className="mkt-section-heading"><div><span className="mkt-eyebrow">Keep the service accountable</span><h3><Activity size={20}/> Operational health</h3></div><button className="mkt-secondary" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{open?'Close operations':'Inspect operations'}</button></div>{open&&<>{error&&<Notice error>{error}</Notice>}<button className="mkt-text-button" disabled={loading} onClick={()=>setRefresh(value=>value+1)}><RefreshCw size={14}/>{loading?'Reading evidence…':'Refresh operational evidence'}</button>{result&&<><p className="mkt-caption">Observed {observedTime(result.operations.observedAt)}. This view reports queue and configuration evidence; provider delivery appears on each campaign.</p><div className="mkt-review-grid"><div><h4>Accounting close</h4><p>{result.readiness.settlement.configured?'Documentary settlement is configured. Independent finance review is required.':'Accounting close is not configured for this environment.'}</p><h4>Booking measurement</h4><p>{result.readiness.conversions.enabled?'Canonical conversion consumer is connected. Delivery receipts still require provider verification.':'Booking conversion delivery is blocked.'}</p>{result.readiness.conversions.blockers.length>0&&<ul>{result.readiness.conversions.blockers.map(code=><li key={code}>{humanStatus(code)}</li>)}</ul>}<p className="mkt-caption">{result.readiness.conversions.limits?.join(' ')}</p></div><div><h4>Pending work</h4>{result.operations.queues.length?<dl className="mkt-review-list">{result.operations.queues.map(queue=><div key={`${queue.kind}:${queue.state}`}><dt>{humanStatus(queue.kind)} · {humanStatus(queue.state)}<small>Oldest: {observedTime(queue.oldest_created_at)}</small></dt><dd>{queue.count}{queue.expired_leases>0?` · ${queue.expired_leases} expired leases`:''}</dd></div>)}</dl>:<p>No pending jobs were observed.</p>}</div></div><h4>Jobs requiring inspection</h4>{result.operations.jobs.length?<div className="mkt-queue-items">{result.operations.jobs.map(job=><article className="mkt-queue-item" key={job.id}><strong>{humanStatus(job.kind)} · campaign {job.campaign_id??'service event'}</strong><span>{humanStatus(job.state)} · attempts {job.attempts}</span>{job.last_error&&<small>{humanStatus(job.last_error)}</small>}<small>Reference {job.id}</small></article>)}</div>:<p>No failed, uncertain or running jobs were observed.</p>}<p className="mkt-caption">An uncertain external write must be reconciled against its recorded provider identity before another write is considered.</p></>}</>}</section>;
}
