import React, {useCallback, useEffect, useRef, useState} from 'react';
import {ArrowDownToLine, Check, FileCheck2, FilePlus2, LockKeyhole, Plus, RefreshCw, ShieldCheck, X} from 'lucide-react';
import {humanStatus, marketingRequest, money, observedTime} from './api';
import type {SettlementDocumentView, SettlementEligibleCampaign, SettlementProposalView} from '../../src/lib/marketing/settlementService';
import type {SettlementDocumentInput, SettlementProposalInput, SettlementReviewInput} from '../../src/lib/marketing/settlementSchemas';
import {settlementMinor, verifySettlementBytes} from './settlementHelpers';
import './SettlementWorkspace.css';
import {GoogleInvoiceImport} from './GoogleInvoiceImport';

type Workspace = {capabilities:{configured:boolean;source:string;automaticProviderFinality:false;policyReference:string;googleInvoiceImport?:boolean};currentOperatorId:number;eligibleCampaigns:SettlementEligibleCampaign[];proposals:SettlementProposalView[];page:{nextCursor:string|null};campaignPage:{nextCursor:number|null}};
type Proposal = SettlementProposalView & {documents:SettlementDocumentView[];review:{reviewerId:number;decision:'APPROVE'|'REJECT';evidence:SettlementReviewInput;createdAt:string}|null};
type Result = {currency?:'INR'|'USD';actualCostMinor:string;chargedCostMinor:string;profitMinor:string;taxMinor:string;returnedMinor:string;platformOverrunMinor:string;finalAt:string};
type HostSummary = {status:string;result:Result|null;createdAt?:string};
const errorMessage = (error:unknown) => error instanceof Error ? error.message : 'The financial evidence could not be loaded.';
const docLabel = (doc:SettlementDocumentView) => `${doc.issuer} · ${doc.externalDocumentId} · ${money(doc.totalMinor,doc.currency)}`;
const kinds:SettlementDocumentInput['kind'][] = ['PROVIDER_INVOICE','CAMPAIGN_BILLING_DETAIL','BILLING_CLOSURE','COST_INVOICE','TAX_STATEMENT'];
const issuers:SettlementDocumentInput['issuer'][] = ['GOOGLE','META','STRIPE','RAZORPAY','ACCOUNTANT'];

async function downloadEvidence(doc:Pick<SettlementDocumentView,'id'|'sha256'|'contentType'>) {
  const token=localStorage.getItem('token');if(!token)throw new Error('Sign in again to read financial evidence.');
  const response=await fetch(`/api/marketing/v2/admin/settlements/documents/${encodeURIComponent(doc.id)}`,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(30000)});
  if(!response.ok)throw new Error('Document access is unavailable. Refresh your financial administrator session.');
  const bytes=await response.arrayBuffer();await verifySettlementBytes(bytes,doc.sha256);
  const suffix=doc.contentType==='application/pdf'?'pdf':doc.contentType==='text/csv'?'csv':'json';
  const url=URL.createObjectURL(new Blob([bytes],{type:doc.contentType}));const link=document.createElement('a');link.href=url;link.download=`encho-evidence-${doc.id}.${suffix}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}

/** Mounted by the admin dashboard; all authority and ledger validation remains on the server. */
export function AdminSettlementWorkspace() {
  const [workspace,setWorkspace]=useState<Workspace|null>(null),[documents,setDocuments]=useState<SettlementDocumentView[]>([]);
  const [documentPage,setDocumentPage]=useState<{nextCursor:string|null}>({nextCursor:null}),[knownDocuments,setKnownDocuments]=useState<SettlementDocumentView[]>([]);
  const [search,setSearch]=useState(''),[querySearch,setQuerySearch]=useState(''),[docSearch,setDocSearch]=useState(''),[queryDocSearch,setQueryDocSearch]=useState('');
  const [cursors,setCursors]=useState<string[]>([]),[campaignCursors,setCampaignCursors]=useState<number[]>([]),[docCursors,setDocCursors]=useState<string[]>([]);
  const query=new URLSearchParams({search:querySearch}),documentQuery=new URLSearchParams({search:queryDocSearch});if(cursors.length)query.set('before',cursors.at(-1)!);if(campaignCursors.length)query.set('campaignBefore',String(campaignCursors.at(-1)));if(docCursors.length)documentQuery.set('before',docCursors.at(-1)!);
  const queryString=query.toString(),docQueryString=documentQuery.toString();
  const [selected,setSelected]=useState<Proposal|null>(null),[tab,setTab]=useState<'review'|'prepare'|'documents'>('review');
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const keys=useRef(new Map<string,string>()),generation=useRef(0);
  const reload=useCallback(async()=>{const sequence=++generation.current;try{
    const [data,docs]=await Promise.all([marketingRequest<Workspace>(`/admin/settlements?${queryString}`),marketingRequest<{documents:SettlementDocumentView[];page:{nextCursor:string|null}}>(`/admin/settlements/documents?${docQueryString}`)]);
    if(!Array.isArray(data?.proposals)||!Array.isArray(data?.eligibleCampaigns)||!data.capabilities||!data.page||!data.campaignPage||!Array.isArray(docs.documents)||!docs.page)throw new Error('The financial workspace response is incomplete.');
    if(sequence===generation.current){setWorkspace(data);setDocuments(docs.documents);setDocumentPage(docs.page);setKnownDocuments(previous=>[...new Map([...previous,...docs.documents].map(d=>[d.id,d])).values()]);setError('');}
  }catch(e){if(sequence===generation.current)setError(errorMessage(e));}finally{if(sequence===generation.current)setLoading(false);}},[queryString,docQueryString]);
  useEffect(()=>{void reload();return()=>{generation.current++;};},[reload]);
  async function open(id:string){setBusy(true);setError('');try{setSelected(await marketingRequest<Proposal>(`/admin/settlements/${id}`));setTab('review');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function mutate(path:string,input:unknown,success:string) {
    setBusy(true);setError('');setNotice('');const scope=path+JSON.stringify(input);if(!keys.current.has(scope))keys.current.set(scope,crypto.randomUUID());
    try{const result=await marketingRequest<any>(path,{method:'POST',headers:{'Idempotency-Key':keys.current.get(scope)!},body:JSON.stringify(input)});keys.current.delete(scope);setNotice(success);await reload();return result;}
    catch(e){setError(errorMessage(e));throw e;}finally{setBusy(false);}
  }
  const run=(work:()=>Promise<unknown>)=>{void work().catch(()=>{/* Error is rendered by mutate. */});};
  const ready=workspace?.capabilities.configured===true;
  return <section className="stl-workspace" data-testid="settlement-workspace"><header className="stl-header"><div><span className="stl-eyebrow">ENCHO / FINANCIAL CLOSE</span><h2>Every cost.<br/><em>Accounted for.</em></h2><p>Connect issued bills to campaign costs. A second finance administrator reviews the evidence before reserved funds are reconciled.</p></div><div className="stl-seal"><ShieldCheck size={28}/><span>Two people.<br/>One immutable record.</span></div></header>
    <div className="stl-strip"><span><LockKeyhole size={15}/> Reserved funds stay protected until accounting close</span><button onClick={()=>{setSelected(null);void reload();}} disabled={busy||loading}><RefreshCw size={15}/> Refresh</button></div>
    {error&&<p className="stl-notice stl-error" role="alert">{error}</p>}{notice&&<p className="stl-notice" role="status">{notice}</p>}
    {loading&&<p className="stl-notice" role="status">Loading financial evidence…</p>}
    {workspace&&!ready&&<p className="stl-notice">Financial close is unavailable until two financial administrators, the accounting procedure and authenticated provider checks are configured. Reserves remain held.</p>}
    {workspace&&<><nav className="stl-tabs" aria-label="Financial close workspace">{(['review','prepare','documents'] as const).map(value=><button key={value} aria-pressed={tab===value} onClick={()=>setTab(value)}>{value==='review'?'Review & close':value==='prepare'?'Prepare a close':'Evidence library'}</button>)}</nav>
      <form className="stl-search" onSubmit={e=>{e.preventDefault();setQuerySearch(search.trim());setCursors([]);setCampaignCursors([]);}}><label>Find campaign or proposal<input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} aria-label="Find campaign or proposal"/></label><button disabled={busy} type="submit">Search</button></form>
      <p className="stl-caption">Accounting procedure: <strong>{workspace.capabilities.policyReference||'Not configured'}</strong>. Documents are sourced by finance administrators. Provider reporting may receive later billing corrections.</p>
      <div hidden={tab!=='documents'}><div className="stl-columns"><div className="stl-source-stack"><GoogleInvoiceImport configured={workspace.capabilities.googleInvoiceImport===true} disabled={busy||!ready} onImport={input=>mutate('/admin/settlements/import/google',input,'Issued Google billing evidence retained. Verify campaign allocations and source documents before independent review.')}/><DocumentForm disabled={busy||!ready} policyReference={workspace.capabilities.policyReference} onSubmit={input=>mutate('/admin/settlements/documents',input,'Document retained with its content fingerprint.').then(()=>undefined)}/></div><section className="stl-card"><span className="stl-eyebrow">Retained documents · page {docCursors.length+1}</span><h3>Evidence library</h3><form className="stl-search" onSubmit={e=>{e.preventDefault();setQueryDocSearch(docSearch.trim());setDocCursors([]);}}><label>Find document or billing account<input value={docSearch} maxLength={100} onChange={e=>setDocSearch(e.target.value)}/></label><button type="submit">Search</button></form><DocumentList documents={documents} onError={setError}/><SettlementPager page={docCursors.length+1} hasNext={!!documentPage.nextCursor} disabled={busy||loading} previous={()=>setDocCursors(v=>v.slice(0,-1))} next={()=>{if(documentPage.nextCursor)setDocCursors(v=>[...v,documentPage.nextCursor!]);}}/></section></div></div>
      <div hidden={tab!=='prepare'}><p className="stl-caption">Load supporting documents from the searchable evidence library. Your draft remains here while you review other tabs.</p><SettlementPager page={campaignCursors.length+1} hasNext={!!workspace.campaignPage.nextCursor} disabled={busy||loading} previous={()=>setCampaignCursors(v=>v.slice(0,-1))} next={()=>{if(workspace.campaignPage.nextCursor)setCampaignCursors(v=>[...v,workspace.campaignPage.nextCursor!]);}}/><ProposalForm key={workspace.capabilities.policyReference} campaigns={workspace.eligibleCampaigns} documents={knownDocuments} disabled={busy||!ready} policyReference={workspace.capabilities.policyReference} onSubmit={async input=>{const result=await mutate('/admin/settlements',input,'Proposal prepared. An independent administrator must verify every document.');await open(result.id);}}/></div>
      {tab==='review'&&<div className="stl-review-layout"><aside className="stl-card stl-queue"><span className="stl-eyebrow">Accounting journal · page {cursors.length+1}</span><h3>Settlement proposals</h3>{!workspace.proposals.length&&<p className="stl-caption">No proposals have been prepared.</p>}{workspace.proposals.map(p=><button key={p.id} disabled={busy} className={selected?.id===p.id?'is-selected':''} onClick={()=>void open(p.id)}><span className="stl-eyebrow">Campaign {p.campaignId} · revision {p.revision}</span><strong>{humanStatus(p.status)}</strong><small>{observedTime(p.createdAt)}</small></button>)}<SettlementPager page={cursors.length+1} hasNext={!!workspace.page.nextCursor} disabled={busy||loading} previous={()=>setCursors(v=>v.slice(0,-1))} next={()=>{if(workspace.page.nextCursor)setCursors(v=>[...v,workspace.page.nextCursor!]);}}/></aside>
      {selected?<ProposalReview key={`${selected.id}:${selected.status}:${selected.fingerprint}:${workspace.currentOperatorId}`} proposal={selected} documents={selected.documents??documents} operatorId={workspace.currentOperatorId} disabled={busy||!ready} onError={setError} onReview={input=>run(async()=>{await mutate(`/admin/settlements/${selected.id}/review`,input,'Independent review recorded.');await open(selected.id);})} onCommit={()=>run(async()=>{await mutate(`/admin/settlements/${selected.id}/commit`,{fingerprint:selected.fingerprint},'Financial close committed. The ledger now records actual costs and released funds.');await open(selected.id);})} onWithdraw={reason=>run(async()=>{await mutate(`/admin/settlements/${selected.id}/withdraw`,{fingerprint:selected.fingerprint,reason},'Proposal withdrawn. Its original evidence and review remain in the journal.');await open(selected.id);})}/>:<div className="stl-empty"><FileCheck2 size={38}/><h3>A considered close.</h3><p>Select a proposal to trace every cost to its source and verify the independent review.</p></div>}</div>}
    </>}
  </section>;
}

function SettlementPager({page,hasNext,disabled,previous,next}:{page:number;hasNext:boolean;disabled:boolean;previous:()=>void;next:()=>void}) {return <div className="stl-pager"><button type="button" disabled={disabled||page===1} onClick={previous}>Previous</button><span>Page {page}</span><button type="button" disabled={disabled||!hasNext} onClick={next}>Next</button></div>;}

function DocumentList({documents,onError}:{documents:SettlementDocumentView[];onError:(value:string)=>void}) {
  const [reading,setReading]=useState('');
  return <div className="stl-doc-list">{!documents.length&&<p className="stl-caption">No billing documents have been retained.</p>}{documents.map(doc=><article key={doc.id}><div><span className="stl-eyebrow">{humanStatus(doc.kind)}</span><strong>{docLabel(doc)}</strong><small>{doc.periodStart} — {doc.periodEnd}</small><code>{doc.sha256}</code></div><button aria-label={`Download ${doc.externalDocumentId}`} disabled={!!reading} onClick={()=>{setReading(doc.id);void downloadEvidence(doc).catch(e=>onError(errorMessage(e))).finally(()=>setReading(''));}}><ArrowDownToLine size={17}/>{reading===doc.id?'Reading…':'Read file'}</button></article>)}</div>;
}

function DocumentForm({disabled,policyReference,onSubmit}:{disabled:boolean;policyReference:string;onSubmit:(input:SettlementDocumentInput)=>Promise<void>}) {
  const [kind,setKind]=useState<SettlementDocumentInput['kind']>('PROVIDER_INVOICE'),[issuer,setIssuer]=useState<SettlementDocumentInput['issuer']>('META');
  const [provider,setProvider]=useState<'GOOGLE'|'META'>('META'),[currency,setCurrency]=useState<'INR'|'USD'>('INR');
  const [file,setFile]=useState<File|null>(null),[localError,setLocalError]=useState(''),[fileKey,setFileKey]=useState(0);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLocalError('');const form=event.currentTarget,data=new FormData(form);try{
    if(!file||file.size===0||file.size>5*1024*1024)throw new Error('Select a complete PDF, CSV or JSON document of at most 5 MiB.');
    const contentType=(file.name.toLowerCase().endsWith('.pdf')?'application/pdf':file.name.toLowerCase().endsWith('.csv')?'text/csv':file.name.toLowerCase().endsWith('.json')?'application/json':null) as SettlementDocumentInput['contentType']|null;
    if(!contentType)throw new Error('Select a PDF, CSV or JSON document.');
    const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let offset=0;offset<bytes.length;offset+=8192)binary+=String.fromCharCode(...bytes.subarray(offset,offset+8192));
    const field=(name:string)=>String(data.get(name)||'').trim();const campaignBound=['CAMPAIGN_BILLING_DETAIL','BILLING_CLOSURE'].includes(kind);
    const input:SettlementDocumentInput={kind,issuer,...(campaignBound?{provider,campaignExternalId:field('campaignExternalId')}:{}),accountId:field('accountId'),externalDocumentId:field('externalDocumentId'),currency,totalMinor:settlementMinor(field('amount')),periodStart:field('periodStart'),periodEnd:field('periodEnd'),issuedAt:new Date(field('issuedAt')).toISOString(),sourceUrl:field('sourceUrl'),description:field('description'),contentType,contentBase64:btoa(binary),...(kind==='BILLING_CLOSURE'?{policyReference}:{})};
    await onSubmit(input);form.reset();setFile(null);setFileKey(v=>v+1);
  }catch(e){setLocalError(errorMessage(e));}}
  return <form className="stl-card stl-form" onSubmit={event=>void submit(event)}><span className="stl-eyebrow">01 / Source evidence</span><h3>Retain the original.</h3><p className="stl-caption">Use the issued document and its actual billing identity. This upload records source provenance; it does not authenticate a document with the provider API.</p>{localError&&<p className="stl-notice stl-error" role="alert">{localError}</p>}<fieldset disabled={disabled}><div className="stl-fields"><label>Document kind<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{kinds.map(k=><option key={k} value={k}>{humanStatus(k)}</option>)}</select></label><label>Issuer<select value={issuer} onChange={e=>setIssuer(e.target.value as typeof issuer)}>{issuers.map(i=><option key={i}>{i}</option>)}</select></label><label>Billing account ID<input name="accountId" required maxLength={255}/></label><label>Issued document reference<input name="externalDocumentId" required maxLength={255}/></label>
    {['CAMPAIGN_BILLING_DETAIL','BILLING_CLOSURE'].includes(kind)&&<><label>Ad provider<select value={provider} onChange={e=>setProvider(e.target.value as typeof provider)}><option>META</option><option>GOOGLE</option></select></label><label>External campaign ID<input name="campaignExternalId" required maxLength={255}/></label></>}
    <label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value as typeof currency)}><option>INR</option><option>USD</option></select></label><label>Document total · {currency}<input name="amount" inputMode="decimal" required/></label><label>Billing period begins<input name="periodStart" type="date" required/></label><label>Billing period ends<input name="periodEnd" type="date" required/></label><label>Issued at · your local time<input name="issuedAt" type="datetime-local" required/></label><label>Source portal URL<input name="sourceUrl" type="url" required maxLength={2000}/></label></div><label>Description & allocation context<textarea name="description" minLength={20} maxLength={3000} required rows={3}/></label><label className="stl-upload"><FilePlus2 size={24}/><span>{file?file.name:'Select the original PDF, CSV or JSON'}</span><input key={fileKey} type="file" accept=".pdf,.csv,.json" required onChange={e=>setFile(e.target.files?.[0]??null)}/><small>Maximum 5 MiB · stored bytes cannot be replaced</small></label><button className="stl-primary" type="submit" disabled={!file||disabled}>Retain document <Plus size={16}/></button></fieldset></form>;
}

type CostDraft={code:string;amount:string;note:string;splits:{documentId:string;amount:string}[]};
function ProposalForm({campaigns,documents,disabled,policyReference,onSubmit}:{campaigns:SettlementEligibleCampaign[];documents:SettlementDocumentView[];disabled:boolean;policyReference:string;onSubmit:(input:SettlementProposalInput)=>Promise<void>}) {
  const [campaignId,setCampaignId]=useState(''),[selectedCampaign,setSelectedCampaign]=useState<SettlementEligibleCampaign|null>(null),[costs,setCosts]=useState<CostDraft[]>([]),[invoiceIds,setInvoiceIds]=useState<string[]>([]),[detail,setDetail]=useState(''),[closure,setClosure]=useState(''),[tax,setTax]=useState(''),[taxDoc,setTaxDoc]=useState(''),[note,setNote]=useState(''),[error,setError]=useState('');
  const campaign=selectedCampaign,currency=campaign?.currency;const choices=campaign&& !campaigns.some(c=>c.campaignId===campaign.campaignId)?[campaign,...campaigns]:campaigns;
  function select(value:string){setCampaignId(value);const chosen=choices.find(c=>String(c.campaignId)===value);setSelectedCampaign(chosen??null);setCosts(chosen?.quoteCosts.map(c=>({code:c.code,amount:'',note:'',splits:[]}))??[]);setInvoiceIds([]);setDetail('');setClosure('');setTax('');setTaxDoc('');setNote('');setError('');}
  function change(index:number,patch:Partial<CostDraft>){setCosts(values=>values.map((v,i)=>i===index?{...v,...patch}:v));}
  const matching=documents.filter(d=>d.currency===currency),providerDocs=matching.filter(d=>d.accountId===campaign?.accountId&&d.issuer===campaign?.provider);
  async function submit(event:React.FormEvent){event.preventDefault();if(!campaign)return;setError('');try{
    const allocations=costs.map(c=>({code:c.code,amountMinor:settlementMinor(c.amount),note:c.note,...(c.splits.length?{invoiceAllocations:c.splits.map(s=>({documentId:s.documentId,amountMinor:settlementMinor(s.amount)}))}:{})}));
    await onSubmit({campaignId:campaign.campaignId,revision:campaign.revision,reservationId:campaign.reservationId,allocations,remittanceTaxMinor:settlementMinor(tax),...(taxDoc?{taxDocumentId:taxDoc}:{}),closures:[{provider:campaign.provider,accountId:campaign.accountId,externalCampaignId:campaign.externalCampaignId,invoiceDocumentIds:invoiceIds,detailDocumentId:detail,closureDocumentId:closure}],policyReference,note});
  }catch(e){setError(errorMessage(e));}}
  return <form className="stl-card stl-form" onSubmit={event=>void submit(event)}><span className="stl-eyebrow">02 / Prepare the accounting close</span><h3>Trace costs to their source.</h3><p className="stl-caption">Quoted amounts are ceilings. Enter actual billed costs from the evidence, including an explicit zero where applicable. The server checks the completed flight, exact provider identity and all unsettled operations.</p>{error&&<p className="stl-notice stl-error" role="alert">{error}</p>}<fieldset disabled={disabled}><label>Paused campaign with an intact reserve<select required value={campaignId} onChange={e=>select(e.target.value)}><option value="">Select a campaign</option>{choices.map(c=><option key={c.campaignId} value={c.campaignId}>{c.title||c.listingTitle} · {c.provider} · revision {c.revision}</option>)}</select></label>{!campaigns.length&&<p className="stl-caption">No paused, reserved campaigns match this page. Search or browse earlier campaigns.</p>}
    {campaign&&<><div className="stl-binding"><span>{campaign.provider} account <strong>{campaign.accountId}</strong></span><span>Campaign <strong>{campaign.externalCampaignId}</strong></span><span>{campaign.flightStart} — {campaign.flightEnd}</span><span>Fixed markup <strong>{campaign.markupBps/100}% of chargeable costs</strong></span></div>
      <div className="stl-costs">{costs.map((cost,index)=><section key={cost.code}><div className="stl-cost-heading"><h4>{humanStatus(cost.code)}</h4><span>Host ceiling {money(campaign.quoteCosts[index].amountMinor,currency)}</span></div><div className="stl-fields"><label>Actual cost · {currency}<input value={cost.amount} inputMode="decimal" required onChange={e=>change(index,{amount:e.target.value})}/></label><label>Allocation notes<textarea value={cost.note} minLength={20} maxLength={3000} required rows={2} onChange={e=>change(index,{note:e.target.value})}/></label></div>{cost.splits.map((split,j)=><div key={j} className="stl-split"><label>Source invoice<select required value={split.documentId} onChange={e=>change(index,{splits:cost.splits.map((s,k)=>k===j?{...s,documentId:e.target.value}:s)})}><option value="">Select an issued document</option>{matching.filter(d=>['PROVIDER_INVOICE','COST_INVOICE','TAX_STATEMENT'].includes(d.kind)).map(d=><option key={d.id} value={d.id}>{docLabel(d)}</option>)}</select></label><label>Amount on this invoice<input required inputMode="decimal" value={split.amount} onChange={e=>change(index,{splits:cost.splits.map((s,k)=>k===j?{...s,amount:e.target.value}:s)})}/></label><button type="button" aria-label={`Remove invoice allocation ${j+1} for ${cost.code}`} onClick={()=>change(index,{splits:cost.splits.filter((_,k)=>k!==j)})}><X size={16}/></button></div>)}<button type="button" className="stl-text-button" disabled={cost.splits.length>=12} onClick={()=>change(index,{splits:[...cost.splits,{documentId:'',amount:''}]})}><Plus size={14}/> Add source invoice allocation</button><p className="stl-caption">Invoice allocations must sum exactly to the actual cost. A cost quoted and settled at zero may have no source invoice.</p></section>)}</div>
      <h4>Close the complete billing period</h4><div className="stl-invoice-checks">{providerDocs.filter(d=>d.kind==='PROVIDER_INVOICE').map(d=><label className="stl-check" key={d.id}><input type="checkbox" checked={invoiceIds.includes(d.id)} onChange={e=>setInvoiceIds(ids=>e.target.checked?[...ids,d.id]:ids.filter(id=>id!==d.id))}/><span>{docLabel(d)}<small>{d.periodStart} — {d.periodEnd}</small></span></label>)}</div><div className="stl-fields"><label>Campaign billing detail<select required value={detail} onChange={e=>setDetail(e.target.value)}><option value="">Select exact campaign detail</option>{providerDocs.filter(d=>d.kind==='CAMPAIGN_BILLING_DETAIL'&&d.metadata.campaignExternalId===campaign.externalCampaignId).map(d=><option key={d.id} value={d.id}>{docLabel(d)}</option>)}</select></label><label>Accounting closure evidence<select required value={closure} onChange={e=>setClosure(e.target.value)}><option value="">Select policy-bound closure</option>{matching.filter(d=>d.kind==='BILLING_CLOSURE'&&d.accountId===campaign.accountId&&d.metadata.provider===campaign.provider&&d.metadata.campaignExternalId===campaign.externalCampaignId).map(d=><option key={d.id} value={d.id}>{docLabel(d)}</option>)}</select></label><label>Separately remitted tax · {currency}<input required inputMode="decimal" value={tax} onChange={e=>setTax(e.target.value)}/><small>Quoted ceiling {money(campaign.quotedTaxMinor,currency)}</small></label><label>Remittance tax statement<select value={taxDoc} onChange={e=>setTaxDoc(e.target.value)}><option value="">None · only if no tax is due</option>{matching.filter(d=>d.kind==='TAX_STATEMENT').map(d=><option key={d.id} value={d.id}>{docLabel(d)}</option>)}</select></label></div><label>Accounting close rationale<textarea required minLength={20} maxLength={3000} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="stl-primary" disabled={disabled||!invoiceIds.length} type="submit">Prepare for independent review <FileCheck2 size={17}/></button></>}
    </fieldset></form>;
}

function ProposalReview({proposal,documents,operatorId,disabled,onError,onReview,onCommit,onWithdraw}:{proposal:Proposal;documents:SettlementDocumentView[];operatorId:number;disabled:boolean;onError:(s:string)=>void;onReview:(input:SettlementReviewInput)=>void;onCommit:()=>void;onWithdraw:(reason:string)=>void}) {
  const [downloaded,setDownloaded]=useState<string[]>([]),[checked,setChecked]=useState<string[]>([]),[note,setNote]=useState(''),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[committing,setCommitting]=useState(false),[reading,setReading]=useState('');
  const evidence=proposal.snapshot.documents,independent=proposal.preparedBy!==operatorId&&!evidence.some(d=>d.uploadedBy===operatorId),pending=proposal.status==='PENDING_REVIEW';
  const reviewed=checked.length===evidence.length&&evidence.every(d=>checked.includes(d.id))&&note.trim().length>=20&&reference.trim().length>=20;
  const currency=proposal.result?.currency||documents.find(d=>evidence.some(e=>e.id===d.id))?.currency;
  function review(decision:'APPROVE'|'REJECT'){onReview({fingerprint:proposal.fingerprint,decision,note,independentVerificationReference:reference,checkedDocuments:evidence.map(d=>({id:d.id,sha256:d.sha256}))});}
  return <section className="stl-card stl-proposal"><div className="stl-title-row"><div><span className="stl-eyebrow">Campaign {proposal.campaignId} / revision {proposal.revision}</span><h3>{humanStatus(proposal.status)}</h3></div><LockKeyhole size={22}/></div><p className="stl-caption">Prepared by finance administrator {proposal.preparedBy} · {observedTime(proposal.createdAt)}</p><code className="stl-fingerprint">{proposal.fingerprint}</code>
    <dl className="stl-amount-list">{proposal.snapshot.input.allocations.map(a=><div key={a.code}><dt>{humanStatus(a.code)}<small className="stl-allocation-note">{a.note}</small>{(a.invoiceAllocations??(a.invoiceDocumentId?[{documentId:a.invoiceDocumentId,amountMinor:a.amountMinor}]:[])).map(source=><small className="stl-allocation-note" key={source.documentId}>{documents.find(d=>d.id===source.documentId)?.externalDocumentId??source.documentId} · {currency?money(source.amountMinor,currency):`${source.amountMinor} minor units`}</small>)}</dt><dd>{currency?money(a.amountMinor,currency):`${a.amountMinor} minor units`}</dd></div>)}<div><dt>Separately remitted tax</dt><dd>{currency?money(proposal.snapshot.input.remittanceTaxMinor,currency):`${proposal.snapshot.input.remittanceTaxMinor} minor units`}</dd></div></dl><p>{proposal.snapshot.input.note}</p>
    <div className="stl-review-documents">{evidence.map(item=>{const doc=documents.find(d=>d.id===item.id);return <article key={item.id}><div><strong>{doc?docLabel(doc):`Retained document ${item.id}`}</strong><code>{item.sha256}</code>{doc&&<><small>{humanStatus(doc.kind)} · {doc.periodStart} — {doc.periodEnd}</small><p className="stl-caption">{doc.metadata.description}</p><a href={doc.metadata.sourceUrl} target="_blank" rel="noreferrer">Open recorded source portal</a></>}</div><button disabled={!!reading||!doc} onClick={()=>{if(!doc)return;setReading(item.id);void downloadEvidence({...doc,sha256:item.sha256}).then(()=>setDownloaded(ids=>[...new Set([...ids,item.id])])).catch(e=>onError(errorMessage(e))).finally(()=>setReading(''));}}><ArrowDownToLine size={16}/>{reading===item.id?'Reading…':'Read file'}</button><label className="stl-check"><input type="checkbox" disabled={!independent||!pending||disabled||!downloaded.includes(item.id)} checked={pending?checked.includes(item.id):!!proposal.review?.evidence.checkedDocuments.some(verified=>verified.id===item.id&&verified.sha256===item.sha256)} onChange={e=>setChecked(ids=>e.target.checked?[...ids,item.id]:ids.filter(id=>id!==item.id))}/><span>I independently verified this exact document, source account and allocation.</span></label>{!doc&&<p className="stl-caption">Document metadata is outside the current library window. Ask the financial operator to load the complete evidence before review.</p>}</article>;})}</div>
    {pending&&<>{!independent&&<p className="stl-notice">An independent finance administrator must review this proposal. Its preparer and document uploaders cannot approve it.</p>}<div className="stl-form"><label>Independent verification reference<textarea disabled={!independent||disabled} minLength={20} maxLength={3000} value={reference} onChange={e=>setReference(e.target.value)} rows={2}/><small>Record where you independently checked the original provider bills and accounting close.</small></label><label>Review reasoning<textarea disabled={!independent||disabled} minLength={20} maxLength={3000} value={note} onChange={e=>setNote(e.target.value)} rows={3}/></label><div className="stl-actions"><button disabled={disabled||!independent||!reviewed} onClick={()=>review('REJECT')}>Reject with evidence</button><button className="stl-primary" disabled={disabled||!independent||!reviewed} onClick={()=>review('APPROVE')}><Check size={16}/> Record independent approval</button></div></div></>}
    {proposal.review&&<div className="stl-notice"><strong>{humanStatus(proposal.review.decision)} · administrator {proposal.review.reviewerId}</strong><p>{proposal.review.evidence.note}</p><small>{proposal.review.evidence.independentVerificationReference}</small></div>}
    {proposal.status==='APPROVED'&&<div className="stl-close"><h4>Commit the reviewed accounting close</h4><p>Encho will recheck provider pause, campaign identity, financial authority and invoice allocations. A successful commit records costs and releases the unused reserve into refundable available funds.</p><label className="stl-check"><input type="checkbox" checked={committing} disabled={disabled} onChange={e=>setCommitting(e.target.checked)}/><span>I am committing this exact independently reviewed evidence fingerprint.</span></label><button className="stl-primary" disabled={disabled||!committing} onClick={onCommit}>Commit financial close <LockKeyhole size={16}/></button></div>}
    {proposal.status==='SETTLED'&&proposal.result&&<SettlementAmounts result={proposal.result} currency={proposal.result.currency}/>}
    {['APPROVED','PENDING_REVIEW'].includes(proposal.status)&&<details className="stl-withdraw"><summary>Withdraw this proposal to correct its evidence</summary><label>Withdrawal reason<textarea value={reason} minLength={20} maxLength={3000} rows={2} onChange={e=>setReason(e.target.value)}/></label><button disabled={disabled||reason.trim().length<20} onClick={()=>onWithdraw(reason)}>Withdraw proposal</button><p className="stl-caption">The original proposal and review remain immutable. Funds stay reserved.</p></details>}
  </section>;
}

function SettlementAmounts({result,currency}:{result:Result;currency:'INR'|'USD'}){return <div className="stl-settled"><span className="stl-eyebrow">Accounting close recorded</span><dl className="stl-amount-list"><div><dt>Verified actual campaign expenses</dt><dd>{money(result.actualCostMinor,currency)}</dd></div><div><dt>Expenses charged within your quote</dt><dd>{money(result.chargedCostMinor,currency)}</dd></div><div><dt>Encho cost-based management fee</dt><dd>{money(result.profitMinor,currency)}</dd></div><div><dt>Separately remitted tax</dt><dd>{money(result.taxMinor,currency)}</dd></div><div><dt>Provider overrun absorbed by Encho</dt><dd>{money(result.platformOverrunMinor,currency)}</dd></div><div className="stl-return"><dt>Unused funds released</dt><dd>{money(result.returnedMinor,currency)}</dd></div></dl><p className="stl-caption">Recorded {observedTime(result.finalAt)}. Released funds are available for reuse or a separate refund request; this close does not itself send a refund to your payment method.</p></div>;}

export function HostSettlementSummary({campaignId,currency,refreshKey}:{campaignId:number|string;currency:'INR'|'USD';refreshKey?:string|number}) {
  const [summary,setSummary]=useState<HostSummary|null>(null),[error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();setSummary(null);setError('');void marketingRequest<HostSummary>(`/campaigns/${encodeURIComponent(String(campaignId))}/settlement`,{signal:controller.signal}).then(value=>{if(!value||typeof value.status!=='string')throw new Error('Financial close data is incomplete.');if(!controller.signal.aborted)setSummary(value);}).catch(e=>{if(!controller.signal.aborted)setError(errorMessage(e));});return()=>controller.abort();},[campaignId,refreshKey]);
  return <section className="stl-host" data-testid="host-settlement-summary"><div className="stl-title-row"><div><span className="stl-eyebrow">Your campaign funds</span><h3>A clear financial close.</h3></div><ShieldCheck size={22}/></div>{error?<p className="stl-notice stl-error" role="alert">{error}</p>:!summary?<p role="status">Loading financial close…</p>:summary.status==='SETTLED'&&summary.result?<SettlementAmounts result={summary.result} currency={summary.result.currency||currency}/>:<><strong>{humanStatus(summary.status)}</strong><p>Campaign funds remain reserved while Encho verifies billed costs and independent accounting approval. A paused ad or a reporting estimate does not establish the final charge.</p></>}</section>;
}
