import { describe,it,expect,vi } from 'vitest';
import { MetaAdsClient } from '../../lib/providers/meta/MetaAdsClient.js';
const credentials={accessToken:'test-access',appSecret:'test-secret',accountId:'123',pageId:'456',pixelId:'789'};
describe('Meta authenticated transport failure boundaries',()=>{
  it('fails missing configuration before HTTP without implicit sandbox',async()=>{const transport=vi.fn();const client=new MetaAdsClient({...credentials,accessToken:''},{fetch:transport});await expect(client.get('act_123')).rejects.toMatchObject({code:'META_CONFIGURATION_REQUIRED'});expect(transport).not.toHaveBeenCalled();});
  it('rejects foreign account paths and injected credential parameters',async()=>{const transport=vi.fn();const client=new MetaAdsClient(credentials,{fetch:transport});await expect(client.post('act_999/campaigns',{})).rejects.toMatchObject({code:'META_OWNERSHIP_MISMATCH'});await expect(client.post('act_123/campaigns',{access_token:'injected'})).rejects.toMatchObject({code:'META_INVALID_ARGUMENT'});expect(transport).not.toHaveBeenCalled();});
  it.each([500,502,503,408])('quarantines HTTP %i writes without echoing provider bodies',async status=>{const transport=vi.fn(async()=>new Response(JSON.stringify({error:{message:'private token'}}),{status}));const client=new MetaAdsClient(credentials,{fetch:transport as typeof fetch});const error=await client.post('act_123/campaigns',{}).catch(e=>e);expect(error).toMatchObject({code:'META_UNKNOWN_OUTCOME',unknownOutcome:true});expect(JSON.stringify(error)).not.toContain('private');expect(transport).toHaveBeenCalledTimes(1);});
  it.each([400,401,403,429])('distinguishes definite HTTP %i rejection',async status=>{const client=new MetaAdsClient(credentials,{fetch:vi.fn(async()=>new Response('{}',{status})) as typeof fetch});await expect(client.post('act_123/campaigns',{})).rejects.toMatchObject({code:'META_REQUEST_REJECTED',unknownOutcome:false});});
  it('times out ignored abort signals and preserves unknown writes',async()=>{const transport=vi.fn(async()=>new Promise<Response>(()=>{}));const client=new MetaAdsClient(credentials,{fetch:transport as typeof fetch,timeoutMs:5});await expect(client.post('act_123/campaigns',{})).rejects.toMatchObject({unknownOutcome:true});expect((transport.mock.calls as any)[0][1].signal.aborted).toBe(true);});
  it('never exposes raw network exception text',async()=>{const client=new MetaAdsClient(credentials,{fetch:vi.fn(async()=>{throw new Error('Authorization Bearer secret');}) as typeof fetch});const error=await client.post('act_123/campaigns',{}).catch(e=>e);expect(error.unknownOutcome).toBe(true);expect(error.message).not.toContain('secret');});
  it('rejects malformed successful write response',async()=>{const client=new MetaAdsClient(credentials,{fetch:vi.fn(async()=>new Response('not JSON',{status:200})) as typeof fetch});await expect(client.post('act_123/campaigns',{})).rejects.toMatchObject({unknownOutcome:true});});
});
