import {afterAll,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {createHash,randomUUID} from 'node:crypto';
import {createLocalPostgresFixture} from './postgres.js';
import {providerFixture,request as googleRequest} from './googleProviderFixture.js';
import {fixture as metaFixture,request as metaRequest,authorized,media} from './metaProviderFixture.js';
import type {ProviderPublishRequest} from '../../lib/providers/types.js';

function story(request:ProviderPublishRequest,google:boolean){
 const bytes=Buffer.from('isolated reviewed image fixture'),hash=createHash('sha256').update(bytes).digest('hex');
 request.metadata!.spatialCreative={version:1,id:randomUUID(),manifestHash:'a'.repeat(64),cards:['vistas','suites','wellness','grounds'].map((section,i)=>({section,title:['Garden','Guest rooms','Dining','Courtyard'][i],imageUrl:'https://cdn.encho.co.in/'+section+'.jpg',imageHash:hash,landingUrl:request.creativeAssets.landingPageUrl+'#'+section})),images:google?[[1080,1080],[1200,628]].map(([width,height])=>({width,height,sha256:hash,data:bytes.toString('base64')})):[]};return request;
}
describe('SP6 provider mutation and association readback',()=>{
 let fixture:Awaited<ReturnType<typeof createLocalPostgresFixture>>;
 beforeAll(async()=>{fixture=await createLocalPostgresFixture();await fixture.pool.query("CREATE TABLE media_assets(id SERIAL PRIMARY KEY,entity_type TEXT,entity_id INT,url TEXT,moderation_status TEXT)");});afterAll(async()=>{await fixture?.close();});
 beforeEach(async()=>{await fixture.pool.query('TRUNCATE media_assets,provider_entities,provider_publishing_transactions,campaign_financial_contracts,host_marketing_campaigns,listings RESTART IDENTITY CASCADE');await fixture.pool.query("INSERT INTO listings(id,user_id,title,slug,publication_status) VALUES(20,10,'Lake House','lake-house','published'); INSERT INTO host_marketing_campaigns VALUES(1,10,20); INSERT INTO campaign_financial_contracts(campaign_id,gross_host_charge,encho_fee_amount,meta_authorized_spend,meta_remaining_authorization,currency) VALUES(1,10500,500,10000,10000,'INR')");await fixture.pool.query("INSERT INTO media_assets(entity_type,entity_id,url,moderation_status) VALUES('listing',20,$1,'approved')",[media]);});
 it('requires independently supplied story authority before any Google mutation',async()=>{const f=providerFixture('OK',authorized),r=await f.provider.createCampaignHierarchy(story(googleRequest(),true),fixture.pool);expect(r.success).toBe(false);expect(f.state.mutations).toBe(0);});
 it('verifies six returned Google asset associations and records acknowledged upload hashes',async()=>{const verifier=vi.fn(async()=>{}),f=providerFixture('OK',authorized,verifier),r=await f.provider.createCampaignHierarchy(story(googleRequest(),true),fixture.pool);expect(r.error).toBeUndefined();expect(r.success).toBe(true);expect(verifier).toHaveBeenCalled();expect(f.state.operations).toHaveLength(19);const metadata=(await fixture.pool.query("SELECT metadata FROM provider_entities WHERE entity_type='CAMPAIGN'")).rows[0].metadata;expect(metadata.spatialAssets).toHaveLength(6);expect(metadata.spatialAssets[4]).toMatchObject({remoteBytesVerified:false,uploadedSha256:expect.stringMatching(/^[a-f0-9]{64}$/)});});
 it('quarantines unapproved Google sitelink readback and never creates a duplicate hierarchy',async()=>{const f=providerFixture('STORY_DRIFT',authorized,async()=>{}),req=story(googleRequest(),true);expect((await f.provider.createCampaignHierarchy(req,fixture.pool)).success).toBe(false);expect((await fixture.pool.query('SELECT publish_status FROM provider_publishing_transactions')).rows[0].publish_status).toBe('RECONCILIATION_REQUIRED');expect((await f.provider.createCampaignHierarchy({...req,idempotencyKey:'fresh-key'},fixture.pool)).success).toBe(false);expect(f.state.mutations).toBe(1);});
 it('creates a paused Meta hierarchy with precisely four reviewed cards and preserved order',async()=>{const f=metaFixture('OK',authorized,async()=>{}),r=await f.provider.createCampaignHierarchy(story(metaRequest(),false),fixture.pool);expect(r.error).toBeUndefined();expect(r.success).toBe(true);const link=f.state.creative.object_story_spec.link_data;expect(link.child_attachments).toHaveLength(4);expect(link.multi_share_optimized).toBe(false);expect(link.multi_share_end_card).toBe(false);expect(f.state.ad).toBe('PAUSED');});
 it('quarantines changed Meta card text',async()=>{const f=metaFixture('STORY_DRIFT',authorized,async()=>{}),r=await f.provider.createCampaignHierarchy(story(metaRequest(),false),fixture.pool);expect(r.success).toBe(false);expect((await fixture.pool.query('SELECT publish_status FROM provider_publishing_transactions')).rows[0].publish_status).toBe('RECONCILIATION_REQUIRED');});
});
