// scripts/google_canary_audit.ts
/**
 * Production Canary Forensic Verification for Google Ads
 * Reads live identifiers for campaign 7107 and compares with local DB.
 * No mutations are performed.
 */
import { googleAdsClient } from "../src/lib/providers/google/GoogleAdsClient.js";
import { Pool } from "pg";
import { logger } from "../src/lib/logger/index.js";

const CAMPAIGN_ID = "7107";

async function fetchLiveResources() {
  const cred = await googleAdsClient.validateMasterCredentials();
  const customerId = cred.mccCustomerId.replace(/-/g, "");
  const queries = [
    { name: "campaign", gaql: `SELECT campaign.id, campaign.resource_name, campaign.name FROM campaign WHERE campaign.id = ${CAMPAIGN_ID}` },
    { name: "campaign_budget", gaql: `SELECT campaign_budget.id, campaign_budget.resource_name, campaign_budget.amount_micros FROM campaign_budget WHERE campaign_budget.id = ${CAMPAIGN_ID}` },
    { name: "ad_group", gaql: `SELECT ad_group.id, ad_group.resource_name, ad_group.name FROM ad_group WHERE campaign.id = ${CAMPAIGN_ID}` },
    { name: "ad_group_ad", gaql: `SELECT ad_group_ad.ad.id, ad_group_ad.resource_name, ad_group_ad.status FROM ad_group_ad WHERE campaign.id = ${CAMPAIGN_ID}` },
  ];
  const results = {} as Record<string, any[]>;
  for (const q of queries) {
    const rows = await googleAdsClient.searchStream(customerId, q.gaql);
    results[q.name] = rows;
  }
  return results;
}

async function fetchLocalRecords(pool: Pool) {
  const client = await pool.connect();
  try {
    const entityRes = await client.query(`SELECT provider, external_id FROM provider_entities WHERE external_id LIKE $1`, [`%${CAMPAIGN_ID}%`]);
    // provider_publishing_transactions does not have a generic external_id column; check relevant external_* columns
    const txnRes = await client.query(`SELECT provider, external_ad_id, external_campaign_id, external_container_id, external_creative_id FROM provider_publishing_transactions WHERE external_ad_id LIKE $1 OR external_campaign_id LIKE $1 OR external_container_id LIKE $1 OR external_creative_id LIKE $1`, [`%${CAMPAIGN_ID}%`]);
    return { entityRows: entityRes.rows, txnRows: txnRes.rows };
  } finally {
    client.release();
  }
}

async function main() {
  try {
    logger.info("Starting Google Ads Canary forensic verification for campaign ID %s", CAMPAIGN_ID);
    const live = await fetchLiveResources();
    const pool = new Pool({ connectionString: process.env.DATABASE_URL });
    const local = await fetchLocalRecords(pool);
    await pool.end();
    const matrix: string[][] = [];
    matrix.push(["Resource Type", "Live Exists", "Local Entity", "Local Txn", "Status"]);
    const types = ["campaign", "campaign_budget", "ad_group", "ad_group_ad"];
    for (const type of types) {
      const liveExists = live[type] && live[type].length > 0 ? "YES" : "NO";
      const entityMatch = local.entityRows.some(r => r.external_id.includes(CAMPAIGN_ID) && r.provider === "google");
      const txnMatch = local.txnRows.some(r => {
        return (
          (r.external_ad_id && r.external_ad_id.includes(CAMPAIGN_ID)) ||
          (r.external_campaign_id && r.external_campaign_id.includes(CAMPAIGN_ID)) ||
          (r.external_container_id && r.external_container_id.includes(CAMPAIGN_ID)) ||
          (r.external_creative_id && r.external_creative_id.includes(CAMPAIGN_ID))
        ) && r.provider === "google";
      });
      const status = liveExists === "YES" && (entityMatch || txnMatch) ? "MATCH" : (liveExists === "YES" ? "MISMATCH" : "MISSING");
      matrix.push([type, liveExists, entityMatch ? "YES" : "NO", txnMatch ? "YES" : "NO", status]);
    }
    const lines = ["# Google Ads Canary Audit Report", `Campaign ID: ${CAMPAIGN_ID}`, "", "## Discrepancy Matrix", "| Resource Type | Live Exists | Local Entity | Local Txn | Status |", "|---|---|---|---|---|"];
    for (let i = 1; i < matrix.length; i++) {
      const row = matrix[i];
      lines.push(`| ${row.join(' | ')} |`);
    }
    lines.push("\n---\n*Generated by automated forensic verification script.*");
    const reportContent = lines.join("\n");
    const fs = await import('fs');
    const reportPath = "./google_canary_audit_report.md";
    fs.writeFileSync(reportPath, reportContent);
    logger.info("Audit report written to %s", reportPath);
  } catch (err) {
    logger.error("Canary audit failed: %s", err);
    process.exit(1);
  }
}

main();
